# Travis CI build file for Swift-Kuery-PostreSQL.
# Swift-Kuery-PostreSQL runs on OS X and Linux (Ubuntu).
# See the following URLs for further details on Travis CI
# https://docs.travis-ci.com/user/customizing-the-build/
# https://docs.travis-ci.com/user/docker/
# https://docs.travis-ci.com/user/multi-os/

# whitelist (branches that should be built)
branches:
  only:
    - master
    - /^issue.*$/

matrix:
  include:
    # - os: linux
    #   dist: xenial
    #   sudo: required
    #   services: docker
    #   env: DOCKER_IMAGE=docker.kitura.net/kitura/swift-ci:4.0.3 SWIFT_SNAPSHOT=4.0.3 DOCKER_PRIVILEGED=true DOCKER_PACKAGES="libpq-dev postgresql postgresql-contrib locales locales-all" CUSTOM_BUILD_SCRIPT=.build-docker
    # - os: linux
    #   dist: xenial
    #   sudo: required
    #   services: docker
    #   env: DOCKER_IMAGE=docker.kitura.net/kitura/swift-ci:4.1.3 SWIFT_SNAPSHOT=4.1.3 DOCKER_PRIVILEGED=true DOCKER_PACKAGES="libpq-dev postgresql postgresql-contrib locales locales-all" CUSTOM_BUILD_SCRIPT=.build-docker
    # - os: linux
    #   dist: xenial
    #   sudo: required
    #   services: docker
    #   env: DOCKER_IMAGE=docker.kitura.net/kitura/swift-ci:4.2.4 SWIFT_SNAPSHOT=4.2.4 DOCKER_PRIVILEGED=true DOCKER_PACKAGES="libpq-dev postgresql postgresql-contrib locales locales-all" CUSTOM_BUILD_SCRIPT=.build-docker
    - os: linux
      dist: xenial
      sudo: required
      services: docker
      env: DOCKER_IMAGE=docker.kitura.net/kitura/swift-ci:5.0.3 SWIFT_SNAPSHOT=5.0.3 DOCKER_PRIVILEGED=true DOCKER_PACKAGES="libpq-dev postgresql postgresql-contrib locales locales-all" CUSTOM_BUILD_SCRIPT=.build-docker
    - os: linux
      dist: xenial
      sudo: required
      services: docker
      env: DOCKER_IMAGE=docker.kitura.net/kitura/swift-ci:5.1 DOCKER_PRIVILEGED=true DOCKER_PACKAGES="libpq-dev postgresql postgresql-contrib locales locales-all" CUSTOM_BUILD_SCRIPT=.build-docker
    - os: linux
      dist: xenial
      sudo: required
      services: docker
      env: DOCKER_IMAGE=docker.kitura.net/kitura/swift-ci:5.3.3 DOCKER_PRIVILEGED=true DOCKER_PRIVILEGED=true DOCKER_PACKAGES="libpq-dev postgresql postgresql-contrib locales locales-all" CUSTOM_BUILD_SCRIPT=.build-docker
    - os: linux
      dist: xenial
      sudo: required
      services: docker
      env: DOCKER_IMAGE=swift:5.1 SWIFT_SNAPSHOT=$SWIFT_DEVELOPMENT_SNAPSHOT DOCKER_PACKAGES="libpq-dev postgresql postgresql-contrib locales locales-all" CUSTOM_BUILD_SCRIPT=.build-docker
    - os: osx
      osx_image: xcode9.2
      sudo: required
      env: SWIFT_SNAPSHOT=4.0.3
    - os: osx
      osx_image: xcode9.4
      sudo: required
      env: SWIFT_SNAPSHOT=4.1.2
    - os: osx
      osx_image: xcode10.1
      sudo: required
      env: SWIFT_SNAPSHOT=4.2.1
    - os: osx
      osx_image: xcode10.2
      sudo: required
      env: SWIFT_SNAPSHOT=5.0.1 JAZZY_ELIGIBLE=true
    - os: osx
      osx_image: xcode11
      sudo: required
    - os: osx
      osx_image: xcode11
      sudo: required
      env: SWIFT_SNAPSHOT=$SWIFT_DEVELOPMENT_SNAPSHOT

services:
  - postgresql

script:
  - ./build.sh
